apiVersion: v1
kind: Pod
metadata:
  name: mc2
spec:
  initContainers:
    - name: ipc
      image: smj8612/mj-ipc:1.3
      command: ["./ipc", "-producer"] 
#      command: [ 'sleep', '60' ]
  containers:
#  - name: producer
#    image: allingeek/ch6_ipc
#    command: ["./ipc", "-producer"]
  - name: consumer
    image: smj8612/mj-ipc:1.3
    command: ["./ipc", "-consumer"]
  restartPolicy: Never